project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
website:
  repo-url: https://github.com/Qufst/Binder_utilisation
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "Use Binder to execute a notebook and render it in a quarto"
  navbar:
    search: true
    tools: 
      - icon: github
        href: https://github.com/Qufst/Binder_utilisation
        text: GitHub

