# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

notebook-links: true
channels: 
  - conda-forge
  - defaults
dependencies: 
  - python=3.10
  - ipykernel
  - papermill
  - jupyter
#  - numpy
#  - pandas
# - seaborn
# - scikit-learn
# - matplotlib